### ISSUE TITLE
onConsentUpdated is called with a string argument

### ISSUE THREAD

**Issue by p3l6** [ketch-com/ketch-react-native#37]
## What did you expect? 

The type declaration for `onConsentUpdated` indicates an object will be passed to the callback. 

```ts
onConsentUpdated?: (consent: Consent) => void;
```

## What actually happens? 

In practice, I am always getting a string, which then has to be unpacked on the client-side with `JSON.parse`.

**Comment by jboileau99** [comment]
@p3l6 Thanks for the report! We're working on a fix and anticipate releasing it this week.

**Comment by max-mathieu** [comment]
@jboileau99 looking at latest code, this has been fixed in v0.6.3 https://github.com/ketch-com/ketch-react-native/releases/tag/v0.6.3
