### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by p3l6** [ketch-com/ketch-react-native#39]
While pulling the package from the github registry works; it would be great if this was also published to the default npm registry.

This would avoid having to configure github registry access in CI.

**Comment by jboileau99** [comment]
@p3l6 Thanks for the suggestion! We've passed this suggestion to our team to get slotted in the roadmap.

**Comment by antonwinter** [comment]
The package is now being published over here now as well [@ketch-com/ketch-react-native](https://www.npmjs.com/package/@ketch-com/ketch-react-native)
